repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.6
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi ]
        args: [--config, pyproject.toml]
      # Run the formatter.
      - id: ruff-format
        args: [--config, pyproject.toml]
        types_or: [ python, pyi ]

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.14.1
#    hooks:
#      - id: mypy

# 安装流程
# terminal 中执行 pip install pre-commit

# 启用hook
# pre-commit install

# 关闭hook
# pre-commit uninstall

# 手动执行 format (git add 之后)
# pre-commit run
