repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black
        entry: black
        types: [ python ]
        require_serial: true
        args:
          - --line-length=160
          - --skip-string-normalization
          - --skip-magic-trailing-comma
        exclude: ^(tests/|logs/|libs/|.venv/|locales/)
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        entry: isort
        language_version: python3
        args:
          - --profile=black
          - --line-length=160
        exclude: ^(tests/|logs/|libs/|\.venv/|locales/)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy

# 安装流程
# terminal 中执行 pip install pre-commit

# 启用hook
# pre-commit install

# 关闭hook
# pre-commit uninstall

# 手动执行 format (git add 之后)
# pre-commit run
